services:
  client:
    container_name: habit_tracker_dev_client
    build: ./client
    image: debug_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  api:
    container_name: habit_tracker_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=getbaked
      - PGHOST=db
      - PGPASSWORD=habitspass
      - PGDATABASE=habits
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: debug_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=habits
      - POSTGRES_USER=getbaked
      - POSTGRES_PASSWORD=habitspass
volumes:
  dbdata:
networks: 
  default:
    name: habit_tracker_api
